import ItemList from "./components/itemList";
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Product List',
  description: 'Generated by create next app',
};

interface Item {
  name: string;
  price: number;
  stockQuantity: number;
}

async function getItems(): Promise<Item[]> {
  const res = await fetch('http://localhost:3000/products', {
    cache: 'no-store',
  }); 
  if (!res.ok) {
    throw new Error('Failed to fetch items');
  }
  return res.json();
}

export default async function Home() {
  const items = await getItems();

  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
        <ItemList items={items} />
      </main>
      <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
      </footer>
    </div>
  );
}